### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by briankasozi** [occn8/intern5#1]
Please share some screenshots for easy assessment

Tuesday we should have our presentation meeting and close of bootcamp/Internship For group 5
@occn8 
@atuhaic 
@bagumablair 
@Allenmabazi

**Comment by occn8** [comment]
![adminHome](https://user-images.githubusercontent.com/49203847/120148016-43477380-c1f0-11eb-9d37-7d7d9417e36c.png)
![contact](https://user-images.githubusercontent.com/49203847/120148021-45113700-c1f0-11eb-8b23-e70c64b6f48a.png)
![editProfile](https://user-images.githubusercontent.com/49203847/120148028-45a9cd80-c1f0-11eb-83a3-842f3926354c.png)
![itemList](https://user-images.githubusercontent.com/49203847/120148032-46426400-c1f0-11eb-9d07-69526fa731f9.png)
![register](https://user-images.githubusercontent.com/49203847/120148034-46dafa80-c1f0-11eb-9a4c-e0237915b5b2.png)
![selectCourse](https://user-images.githubusercontent.com/49203847/120148035-47739100-c1f0-11eb-97ea-a3cf47f44e88.png)
![signIn](https://user-images.githubusercontent.com/49203847/120148037-480c2780-c1f0-11eb-89bf-70cf41d1a9df.png)
![studentHome](https://user-images.githubusercontent.com/49203847/120148042-48a4be00-c1f0-11eb-8d36-421245cff648.png)

**Comment by atuhaic** [comment]
Hello Mr. Brian,
At what time are we meeting tomorrow?
